# Generated by Django 5.0.6 on 2024-05-09 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_location_remove_userprofile_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='donation_location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.location'),
        ),
    ]
